apiVersion: scope.github.com/v1alpha
kind: ScopeDoctorCheck
metadata:
  name: path-exists-fix-in-scope-dir
spec:
  check:
    target: ./scripts/fail-first-call path-exists-fix-in-scope-dir
  fix:
    target: ./scripts/truey
  description: Check your shell for basic functionality
  help: You're shell does not have a path env. Reload your shell.
