on:
  push:
    branches:
      - main

name: Main Build

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - name: cargo build
        run: cargo build
      - name: cargo check
        run: cargo check
      ## Cargo test
      - name: cargo test
        run: cargo test
      ## Cargo fmt
      - run: rustup component add rustfmt
      - name: cargo fmt
        run:  cargo fmt --all -- --check
      ## Cargo clippy
      - name: cargo clippy
        run: cargo clippy -- -D warnings

